server:
  port: 8085
  servlet:
    context-path: /cloud

cloud:
  aws:
    credentials:
      access-key: your_access_key
      secret-key: your_secret_key
    region:
      static: ap-south-1
    stack:
      auto: false
  bucketName: your_bucket_name

spring:
  config:
    activeate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 10MB
      max-request-size: 10MB
