server:
  port: 8080
  servlet:
    context-path: /cloud
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 50MB
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      access-key: your_access_key
      secret-key: your_secret_key
    region:
      static: ap-south-1
    stack:
      auto: false
  bucketName: your_bucket_name

#========LOGGING=====================
logging.file.name: /home/ubuntu/logs/app.log
logging.level.com.sas: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
